package com.chatbot.platform.api.controller;

import com.chatbot.platform.api.dto.common.ApiResponse;
import com.chatbot.platform.api.dto.common.PageResponse;
import com.chatbot.platform.api.dto.message.MessageResponse;
import com.chatbot.platform.api.dto.message.SendMessageRequest;
import com.chatbot.platform.core.service.ChatService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.util.UUID;

/**
 * REST controller for message retrieval and submission in standalone no-auth mode.
 */
@RestController
@RequestMapping("/api/v1/conversations/{conversationId}/messages")
public class MessageController {

    private final ChatService chatService;

    public MessageController(ChatService chatService) {
        this.chatService = chatService;
    }

    /**
     * Submits a user message to the conversation in standalone mode.
     */
    @PostMapping
    public ResponseEntity<ApiResponse<MessageResponse>> sendMessage(
        @PathVariable("conversationId") UUID conversationId,
        @Valid @RequestBody SendMessageRequest request
    ) {
        MessageResponse response = chatService.sendMessage(conversationId, request);
        return ResponseEntity.status(HttpStatus.CREATED)
            .body(ApiResponse.success("Message sent successfully", response));
    }

    /**
     * Streams an assistant response using Server-Sent Events (SSE) in standalone mode.
     * Progressively emits content chunks as generated by the underlying AI Provider.
     */
    @PostMapping(value = "/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public ResponseEntity<SseEmitter> streamMessage(
        @PathVariable("conversationId") UUID conversationId,
        @Valid @RequestBody SendMessageRequest request
    ) {
        return ResponseEntity.ok()
            .contentType(MediaType.TEXT_EVENT_STREAM)
            .body(chatService.streamMessage(conversationId, request));
    }

    /**
     * Retrieves paginated messages for the conversation in sequential order in standalone mode.
     */
    @GetMapping
    public ResponseEntity<ApiResponse<PageResponse<MessageResponse>>> getMessages(
        @PathVariable("conversationId") UUID conversationId,
        @RequestParam(name = "page", defaultValue = "0") int page,
        @RequestParam(name = "size", defaultValue = "50") int size
    ) {
        PageResponse<MessageResponse> response = chatService.getMessages(conversationId, page, size);
        return ResponseEntity.ok(ApiResponse.success(response));
    }
}
